### ISSUE TITLE
@references

### ISSUE THREAD

**Issue by gt3389b** [lifthrasiir/cson#2]
Our development team has been heavily using CSON for configuration files.  In the evolution of its use, the development team has asked for keys to 'reference' other key values.  I.e. rather than duplicating a section of text for identical data, the use of @data as a pointer. 

Given the ask, I've added initial support to python-cson to support @reference syntax.  I would like to formally roll this back into the CSON syntax as I think it is a valuable feature.  I want your thoughts on how to update your README.md to reflect such a feature.

E.g. { a: { name: "python-cson" }, b: @a }

**Comment by johan** [comment]
Request: try to wrap at-something references here with backticks (i e: `@data`, `@reference`, `@a`), so we don't bug github users by the same name with irrelevant notifications that are not about them. It is the generous thing to do.
